export const PAYMENT_STATES = Object.freeze({
  CREATED: 'CREATED', PENDING: 'PENDING', AUTHORIZED: 'AUTHORIZED', CAPTURED: 'CAPTURED',
  FAILED: 'FAILED', UNKNOWN: 'UNKNOWN', REFUNDED: 'REFUNDED',
})

export const ORDER_STATES = Object.freeze({
  PENDING_PAYMENT: 'PENDING_PAYMENT', PAID: 'PAID', PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REVIEW: 'PAYMENT_REVIEW', CANCELLED: 'CANCELLED',
})

export const PAYMENT_STATE_VALUES = Object.values(PAYMENT_STATES)
export const ORDER_STATE_VALUES = Object.values(ORDER_STATES)
